"""
Query and Response Domain Models
==================================

Purpose:
    Internal representations of a user query and the system's response.
    These models flow through the RAG pipeline as a shared state object,
    accumulating populated fields at each stage from reformulation through
    to generation.

    Flow of field population:
        QueryContext built by RAGPipeline:
            raw_query, session_id, document_ids, query_id  ← step 1
            standalone_query                               ← step 3 (reformulation)
            query_embedding                                ← step 4 (embedding)
            formatted_history                              ← step 8 (memory read)
            reranker_applied, cache_hit                    ← steps 6, 2

Models:

    QueryContext:
        The enriched query object that accumulates state across pipeline stages.

        Attributes:
            raw_query: str
                The user's original question as received from the API.

            standalone_query: str
                The reformulated query after conversational context resolution.
                Equals raw_query on first turn; resolves pronouns/references
                on follow-ups (e.g., "What about its revenue?" becomes
                "What is Acme Corp's Q3 2024 revenue?").

            query_id: str
                UUID4 generated by RAGPipeline at the start of each run().
                Propagated through all steps for request tracing and
                used as the query_id in API responses and SSE events.

            session_id: str
                The session this query belongs to.

            document_ids: list[str]
                Document scope for retrieval. Resolved from session +
                optional per-request override.

            query_embedding: list[float] | None
                The 1536-dimensional embedding of standalone_query.
                None until populated by EmbeddingCache.get_or_embed().

            formatted_history: str
                Pre-built conversation history string for prompt injection.
                Empty string on first turn. Populated by
                MemoryManager.get_formatted_history() before generation.
                Token-bounded to MEMORY_TOKEN_BUDGET.

            reranker_applied: bool
                True if RerankerService was invoked for this query.
                Set by RAGPipeline after the reranking step.
                Stored in RetrievalMetadata for diagnostics.

            cache_hit: bool
                True if this answer was served from ResponseCache.
                False for all freshly generated answers.
                Set by RAGPipeline; propagated to GeneratedAnswer.

    RetrievedContext:
        The set of chunks retrieved and ranked for a query.

        Attributes:
            chunks: list[ScoredChunk]
                Final ranked list of chunks (after threshold + rerank + MMR).
                Length ≤ top_k.

            retrieval_metadata: RetrievalMetadata
                Typed diagnostics object (see app.schemas.metadata).
                Replaces the raw dict used previously; field names are
                validated and documented in one place.

    ScoredChunk:
        A chunk paired with its relevance scores from each ranking stage.

        Attributes:
            chunk: Chunk
                The chunk domain object with text and metadata.

            similarity_score: float
                The primary relevance score used for final ranking.
                After reranking: this is the reranker score.
                Without reranking: this is the bi-encoder cosine score.
                Range: 0.0 to 1.0 (or arbitrary float for cross-encoders).

            bi_encoder_score: float
                The original cosine similarity score from the vector search.
                Preserved even after reranking for diagnostic comparison.
                Allows analysis of reranker impact (how much did it reorder?).

            rerank_score: float | None
                The raw score from the cross-encoder or Cohere Rerank API.
                None if reranker was not applied.
                Distinct from similarity_score (which is normalised to [0,1]).

            rank: int
                Final position in the ranked list (1-based).
                Reflects post-reranking, post-MMR ordering.

    GeneratedAnswer:
        The final response object returned by the pipeline.

        Attributes:
            answer_text: str
                The LLM-generated answer grounded in retrieved context.

            citations: list[Citation]
                Structured source references extracted from the answer.

            confidence: float
                Heuristic confidence: 0.0 (no relevant context) to 1.0.
                Derived from mean similarity_score of retrieved chunks,
                LLM uncertainty signals, and citation density.

            query_id: str
                Propagated from QueryContext for response tracing.

            cache_hit: bool
                True if answer was served from ResponseCache without
                running the full pipeline. False for fresh generation.

            retrieval_context: RetrievedContext
                The full retrieval result including chunks and metadata.
                Included for transparency and debugging.

            pipeline_metadata: PipelineMetadata
                End-to-end timing and diagnostics for the full run.
                Latency breakdown by stage, model names used, etc.

    Citation:
        A single source reference within an answer.

        Attributes:
            document_name: str
                Original PDF filename.
            page_numbers: list[int]
                Pages where the cited information appears.
            chunk_index: int
                Zero-based position in the document.
            chunk_id: str
                Unique chunk identifier for auditability.
            excerpt: str
                Short (≤200 char) excerpt from the source chunk.

    PipelineMetadata:
        End-to-end diagnostic data for a single pipeline run.

        Attributes:
            query_id: str
            total_time_ms: float
                Wall-clock time from run() entry to GeneratedAnswer return.
            reformulation_time_ms: float
                Time spent in query reformulation (0 for first-turn queries).
            embedding_time_ms: float
                Time to embed the query (near 0 on cache hit).
            retrieval_time_ms: float
                Time for vector search + threshold filtering.
            reranking_time_ms: float
                Time for cross-encoder reranking (0 if disabled).
            mmr_time_ms: float
                Time for MMR diversity selection.
            generation_time_ms: float
                Time for LLM generation (0 on response cache hit).
            memory_read_time_ms: float
                Time to build formatted history from MemoryManager.
            memory_write_time_ms: float
                Time to persist the new turn.
            embedding_cache_hit: bool
            response_cache_hit: bool
            reranker_backend: str
                "cohere" | "cross_encoder" | "none"
            llm_model: str
                Model name used for generation (e.g., "gpt-4o").
            embedding_model: str
                Model name used for embedding (e.g., "text-embedding-3-small").

Dependencies:
    - dataclasses
    - app.models.chunk (Chunk)
    - app.models.session (ConversationTurn)
    - app.schemas.metadata (RetrievalMetadata)
"""
